development:
  mode: sandbox
  client_id: AfeIOMG7NZS1kTvBJkcsZDZSb5P14TwKT6zcN3ghVBK6OY-0QdLHKdUpw1oQJlRcHbKSUTPYcKe_Zmij
  client_secret: EBv9wxprH7dFfvW_-etcWAzAxG6a3WX_gM5uQ3kB8yOUAfwirVMmjSKirG13rVhsuVjUxtieVvADcp_F