# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'open-uri'

lorem_ipsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue, pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est. Etiam sit amet lectus quis est congue mollis. Phasellus congue lacus eget neque. Phasellus ornare, ante vitae consectetuer consequat, purus sapien ultricies dolor, et mollis pede metus eget nisi. Praesent sodales velit quis augue. Cras suscipit, urna at aliquam rhoncus, urna quam viverra nisi, in interdum massa nibh nec erat.
Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur?
At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."

pic1 = File.new('app/assets/images/0e4fb6e75a40f3ac328f8fe2e841898e.jpg')
pic2 = File.new('app/assets/images/c8e7e9a120f19bc434a4fce5fcf83e4d.jpg')
pic3 = File.new('app/assets/images/harold-0.jpg')
pic4 = File.new('app/assets/images/hYE8QQO.jpg')


News.create([{title: "News nr 1", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 2", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 3", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 4", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 5", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 6", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 7", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 8", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 9", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 10", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 11", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 12", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 13", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 14", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 15", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 16", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 17", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 18", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 19", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 20", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 21", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 22", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 23", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 24", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 25", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 26", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 27", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 28", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 29", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 30", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 31", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 32", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 33", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 34", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 35", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 36", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 37", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 38", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 39", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 40", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 41", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 42", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 43", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 44", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 45", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 46", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 47", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 48", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 49", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 50", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 51", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 52", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 53", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 54", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 55", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 56", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 57", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 58", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 59", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 60", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 61", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 62", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 63", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 64", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 65", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 66", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 67", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 68", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 69", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 70", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 71", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 72", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 73", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 74", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 75", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 76", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 77", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 78", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 79", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 80", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 81", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 82", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 83", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 84", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 85", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 86", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 87", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 88", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 89", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 90", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 91", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 92", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 93", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 94", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 95", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 96", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 97", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 98", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 99", content: lorem_ipsum, add_date: Time.now, image: pic4},
             {title: "News nr 100", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 101", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 102", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 103", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 104", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 105", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 106", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 107", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 108", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 109", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 110", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 111", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 112", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 113", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 114", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 115", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 116", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 117", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 118", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 119", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 120", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 121", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 122", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 123", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 124", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 125", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 126", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 127", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 128", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 129", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 130", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 131", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 132", content: lorem_ipsum, add_date: Time.now, image: pic2},
             {title: "News nr 133", content: lorem_ipsum, add_date: Time.now, image: pic3},
             {title: "News nr 134", content: lorem_ipsum, add_date: Time.now, image: pic1},
             {title: "News nr 135", content: lorem_ipsum, add_date: Time.now, image: pic3}])

cities = City.create([{name: "Alesund"}, {name: "Amsterdam"}, {name: "Aberdeen"}, {name: "Alicante"}, {name: "Ateny"},
                      {name: "Atlanta"}, {name: "Barcelona"}, {name: "Bari"}, {name: "Bazylea"}, {name: "Bejrut"},
                      {name: "Belgrad"}, {name: "Bergen"}, {name: "Belfast"}, {name: "Berlin"}, {name: "Berno"},
                      {name: "Bilbao"}, {name: "Birmingham"}, {name: "Bolonia"}, {name: "Bordeaux"}, {name: "Boston"},
                      {name: "Bristol"}, {name: "Bruksela"}, {name: "Budapeszt"}, {name: "Bukareszt"}, {name: "Burgas"},
                      {name: "Calgary"}, {name: "Charlotte"}, {name: "Chicago"}, {name: "Cincinnati"}, {name: "Cleveland"},
                      {name: "Dallas"}, {name: "Denver"}, {name: "Detroit"}, {name: "Doha"}, {name: "Finningley"},
                      {name: "Dortmund"}, {name: "Dubaj"}, {name: "Dublin"}, {name: "Dusseldorf"}, {name: "Edinburgh"},
                      {name: "Eindhoven"}, {name: "Erywań"}, {name: "Filadelfia"}, {name: "Florencja"}, {name: "Fort Lauderdale"},
                      {name: "Frankfurt"}, {name: "Genewa"}, {name: "Genua"}, {name: "Glasgow"}, {name: "Göteborg"},
                      {name: "Graz"}, {name: "Halifax"}, {name: "Hamburg"}, {name: "Helsinki"}, {name: "Heraklion"},
                      {name: "Honolulu"}, {name: "Houston"}, {name: "Indianapolis"}, {name: "Innsbruck"}, {name: "Inverness"},
                      {name: "Istambuł"}, {name: "Kaliningrad"}, {name: "Keflavik"}, {name: "Kijów"}, {name: "Klagenfurt"},
                      {name: "Kopenhaga"}, {name: "Korfu"}, {name: "Koszyce"}, {name: "Kraków"}, {name: "Kutaisi"},
                      {name: "Larnaka"}, {name: "Las Vegas"}, {name: "Linz"}, {name: "Liverpool"}, {name: "Lizbona"},
                      {name: "Ljubljana"}, {name: "Londyn"}, {name: "Los Angeles"}, {name: "Luksemburg"}, {name: "Lwów"},
                      {name: "Lyon"}, {name: "Madryt"}, {name: "Malaga"}, {name: "Malmo"}, {name: "Luqa"},
                      {name: "Manchester"}, {name: "Marsylia"}, {name: "Melbourne"}, {name: "Miami"}, {name: "Mediolan"},
                      {name: "Minneapolis"}, {name: "Mińsk"}, {name: "Montreal"}, {name: "Moskwa"}, {name: "Monachium"},
                      {name: "Neapol"}, {name: "Nicea"}, {name: "Nowy Orlean"}, {name: "Nowy Jork"}, {name: "Odessa"},
                      {name: "Orlando"}, {name: "Osaka"}, {name: "Oslo"}, {name: "Ottawa"}, {name: "Palma de Mallorca"},
                      {name: "Paryż"}, {name: "Pekin"}, {name: "Phoenix"}, {name: "Pittsburgh"}, {name: "Portland"},
                      {name: "Porto"}, {name: "Praga"}, {name: "Quebec"}, {name: "Ryga"}, {name: "Rzym"},
                      {name: "Salt Lake City"}, {name: "Salzburg"}, {name: "Saint John`s"}, {name: "Saint Louis"},
                      {name: "San Diego"}, {name: "San Francisco"}, {name: "Sankt Petersburg"}, {name: "Saskatoon"},
                      {name: "Seattle"}, {name: "Sofia"}, {name: "Split"}, {name: "Stavanger"}, {name: "Stuttgart"},
                      {name: "Sztokholm"}, {name: "Sydney"}, {name: "Tallinn"}, {name: "Tampa"}, {name: "Tel Aviv"},
                      {name: "Tokio"}, {name: "Toronto"}, {name: "Tuluza"}, {name: "Trieste"}, {name: "Tunis"},
                      {name: "Turyn"}, {name: "Vancouver"}, {name: "Wenecja"}, {name: "Werona"}, {name: "Wiedeń"},
                      {name: "Wilno"}, {name: "Warszawa"}, {name: "Waszyngton"}, {name: "Winnipeg"}, {name: "Zagrzeb"},
                      {name: "Zurych"}])

airports = Airport.create([{city: cities[0], name: "Vigra", IATA: "AES"},
                           {city: cities[1], name: "Schiphol", IATA: "AMS"},
                           {city: cities[2], name: "Aberdeen Airport", IATA: "ABZ"},
                           {city: cities[3], name: "Alicante-Elche", IATA: "ALC"},
                           {city: cities[4], name: "Eleftherios Venizelos International", IATA: "ATH"},
                           {city: cities[5], name: "William B. Hartsfield", IATA: "ATL"},
                           {city: cities[6], name: "El Prat", IATA: "BCN"},
                           {city: cities[7], name: "Bari Palese \"Karol Wojtyla\" Airport", IATA: "BRI"},
                           {city: cities[8], name: "EuroAirport", IATA: "BSL"},
                           {city: cities[9], name: "Rafic Hariri Intl", IATA: "BEY"},
                           {city: cities[10], name: "Nikola Tesla Intl Airport", IATA: "BEG"},
                           {city: cities[11], name: "Flesland", IATA: "BGO"},
                           {city: cities[12], name: "Belfast City Airport", IATA: "BHD"},
                           {city: cities[13], name: "Tegel", IATA: "TXL"},
                           {city: cities[14], name: "Belp", IATA: "BRN"},
                           {city: cities[15], name: "Sondica", IATA: "BIO"},
                           {city: cities[16], name: "International", IATA: "BHX"},
                           {city: cities[17], name: "Guglielmo Marconi", IATA: "BLQ"},
                           {city: cities[18], name: "Merignac", IATA: "BOD"},
                           {city: cities[19], name: "Logan International", IATA: "BOS"},
                           {city: cities[20], name: "Dyce", IATA: "BRS"},
                           {city: cities[21], name: "Brussels Airport", IATA: "BRU"},
                           {city: cities[21], name: "Charleroi Brussels South", IATA: "CRL"},
                           {city: cities[22], name: "Ferihegy", IATA: "BUD"},
                           {city: cities[23], name: "Otopeni International-Henri Coanda", IATA: "OTP"},
                           {city: cities[24], name: "Dyce", IATA: "BOJ"},
                           {city: cities[25], name: "Calgary International Airport", IATA: "YYC"},
                           {city: cities[26], name: "Charlotte / Douglas International Airport", IATA: "CLT"},
                           {city: cities[27], name: "O`Hare International Airport", IATA: "ORD"},
                           {city: cities[28], name: "Cincinnati / Northern Kentucky International Airport", IATA: "CVG"},
                           {city: cities[29], name: "Cleveland-Hopkins International Airport", IATA: "CLE"},
                           {city: cities[30], name: "Dallas / Fort Worth International Airport", IATA: "DFW"},
                           {city: cities[31], name: "Denver International Airport", IATA: "DEN"},
                           {city: cities[32], name: "Detroit City Airport", IATA: "DET"},
                           {city: cities[33], name: "Hamad International Airport", IATA: "DOH"},
                           {city: cities[34], name: "Robin Hood Doncaster Sheffield Airport", IATA: "DSA"},
                           {city: cities[35], name: "Wickede", IATA: "DTM"},
                           {city: cities[36], name: "Dubai International Airport", IATA: "DXB"},
                           {city: cities[36], name: "Al Makhtoum International Airport", IATA: "DWC"},
                           {city: cities[37], name: "EIDW", IATA: "DUB"},
                           {city: cities[38], name: "Flughafen Düsseldorf", IATA: "DUS"},
                           {city: cities[39], name: "Turnhouse", IATA: "EDI"},
                           {city: cities[40], name: "Eindhoven Airport", IATA: "EIN"},
                           {city: cities[41], name: "Zvarnots", IATA: "EVN"},
                           {city: cities[42], name: "Philadelphia International Airport", IATA: "PHL"},
                           {city: cities[43], name: "Peretola", IATA: "FLR"},
                           {city: cities[44], name: "Fort Lauderdale / Hollywood International Airport", IATA: "FLL"},
                           {city: cities[45], name: "Frankfurt Airport", IATA: "FRA"},
                           {city: cities[45], name: "Frankfurt-Hahn Airport", IATA: "HHN"},
                           {city: cities[46], name: "Cointrin", IATA: "GVA"},
                           {city: cities[47], name: "Sestri", IATA: "GOA"},
                           {city: cities[48], name: "Glasgow Airport", IATA: "GLA"},
                           {city: cities[49], name: "Landvetter", IATA: "GOT"},
                           {city: cities[50], name: "Thalerhof", IATA: "GRZ"},
                           {city: cities[51], name: "Halifax International Airport", IATA: "YHZ"},
                           {city: cities[52], name: "Fuhlsbuettel", IATA: "HAM"},
                           {city: cities[53], name: "Vantaa", IATA: "HEL"},
                           {city: cities[54], name: "Nikos Kazantzakis", IATA: "HER"},
                           {city: cities[55], name: "Honolulu International Airport", IATA: "MCO"},
                           {city: cities[56], name: "George Bush Intercontinental", IATA: "IAH"},
                           {city: cities[57], name: "Indianapolis International Airport", IATA: "IND"},
                           {city: cities[58], name: "Kranebitten", IATA: "INN"},
                           {city: cities[59], name: "Dalcross", IATA: "INV"},
                           {city: cities[60], name: "Ataturk", IATA: "IST"},
                           {city: cities[61], name: "Kaliningrad", IATA: "KGD"},
                           {city: cities[62], name: "Keflavik International Airport", IATA: "KEF"},
                           {city: cities[63], name: "Borispol", IATA: "KBP"},
                           {city: cities[64], name: "Klagenfurt", IATA: "KLU"},
                           {city: cities[65], name: "Kastrup", IATA: "CPH"},
                           {city: cities[66], name: "Ioannis Kapodistrias", IATA: "CFU"},
                           {city: cities[67], name: "Koszyce International Airport", IATA: "KSC"},
                           {city: cities[68], name: "Balice / im. Jana Pawła II", IATA: "KRK"},
                           {city: cities[69], name: "Kopitnari", IATA: "KUT"},
                           {city: cities[70], name: "Larnaka", IATA: "LCA"},
                           {city: cities[71], name: "Mc Carran International Airport", IATA: "LAS"},
                           {city: cities[72], name: "Hoersching", IATA: "LNZ"},
                           {city: cities[73], name: "John Lennon Intl Airport", IATA: "LPL"},
                           {city: cities[74], name: "Portela", IATA: "LIS"},
                           {city: cities[75], name: "Brnik", IATA: "LJU"},
                           {city: cities[76], name: "Heathrow", IATA: "LHR"},
                           {city: cities[76], name: "Gatwick", IATA: "LGW"},
                           {city: cities[76], name: "London City Airport", IATA: "LCY"},
                           {city: cities[76], name: "Luton International Airport", IATA: "LTN"},
                           {city: cities[76], name: "Stansted", IATA: "STN"},
                           {city: cities[77], name: "Los Angeles International Airport", IATA: "LAX"},
                           {city: cities[78], name: "Hoersching", IATA: "LUX"},
                           {city: cities[79], name: "Lviv", IATA: "LWO"},
                           {city: cities[80], name: "Satolas", IATA: "LYS"},
                           {city: cities[81], name: "Barajas", IATA: "MAD"},
                           {city: cities[82], name: "Malaga Costa del Sol Airport", IATA: "AGP"},
                           {city: cities[83], name: "Sturup", IATA: "MMX"},
                           {city: cities[84], name: "Malta International Airport", IATA: "MLA"},
                           {city: cities[85], name: "Ringway", IATA: "MAN"},
                           {city: cities[86], name: "Marignane", IATA: "MRS"},
                           {city: cities[87], name: "Tullamarine", IATA: "MEL"},
                           {city: cities[88], name: "Miami International Airport", IATA: "MIA"},
                           {city: cities[89], name: "Malpensa", IATA: "MXP"},
                           {city: cities[89], name: "Linate", IATA: "LIN"},
                           {city: cities[89], name: "Bergamo-Orio Al Serio", IATA: "BGY"},
                           {city: cities[90], name: "Minneapolis St. Paul International Airport", IATA: "MSP"},
                           {city: cities[91], name: "Minsk International Airport", IATA: "MSQ"},
                           {city: cities[92], name: "Pierre Elliot Trudeau International Airport", IATA: "YUL"},
                           {city: cities[92], name: "Mirabel", IATA: "YMX"},
                           {city: cities[93], name: "Sheremyetyevo", IATA: "SVO"},
                           {city: cities[94], name: "Franz Josef Strauss", IATA: "MUC"},
                           {city: cities[95], name: "Capodichino", IATA: "NAP"},
                           {city: cities[96], name: "Cote d`Azur", IATA: "NCE"},
                           {city: cities[97], name: "New Orleans International Airport", IATA: "MSY"},
                           {city: cities[98], name: "Kennedy International Airport", IATA: "JFK"},
                           {city: cities[98], name: "Newark International Airport", IATA: "EWR"},
                           {city: cities[98], name: "La Guardia", IATA: "LGA"},
                           {city: cities[99], name: "Odessa", IATA: "ODS"},
                           {city: cities[100], name: "Orlando International Airport", IATA: "MCO"},
                           {city: cities[101], name: "Kansai", IATA: "KIX"},
                           {city: cities[102], name: "Gardermoen", IATA: "OSL"},
                           {city: cities[102], name: "Oslo Torp Lufthavn", IATA: "TRF"},
                           {city: cities[103], name: "Ottawa International Ontario", IATA: "YOW"},
                           {city: cities[104], name: "Son San Juan", IATA: "PMI"},
                           {city: cities[105], name: "Charles de Gaulle", IATA: "CDG"},
                           {city: cities[105], name: "Orly", IATA: "ORY"},
                           {city: cities[105], name: "Beauvais-Tille Airport", IATA: "BVA"},
                           {city: cities[105], name: "Le Bourget", IATA: "LBG"},
                           {city: cities[106], name: "Capital International Airport", IATA: "PEK"},
                           {city: cities[107], name: "Sky Harbor International Airport", IATA: "PHX"},
                           {city: cities[108], name: "Pittsburgh International Airport", IATA: "PIT"},
                           {city: cities[109], name: "Portland International Airport", IATA: "PDX"},
                           {city: cities[110], name: "Francisco Sa Carneiro Airport", IATA: "OPO"},
                           {city: cities[111], name: "Ruzyne", IATA: "PRG"},
                           {city: cities[112], name: "Quebec", IATA: "YQB"},
                           {city: cities[113], name: "International Airport", IATA: "RIX"},
                           {city: cities[114], name: "Fiumicino-Leonardo da Vinci", IATA: "FCO"},
                           {city: cities[114], name: "Ciampino", IATA: "CIA"},
                           {city: cities[115], name: "Salt Lake City International Airport", IATA: "SLC"},
                           {city: cities[116], name: "Wolfgang Amadeus Mozart", IATA: "SZG"},
                           {city: cities[117], name: "St. John`s", IATA: "YYT"},
                           {city: cities[118], name: "Lambert-St. Louis International Airport", IATA: "STL"},
                           {city: cities[119], name: "San Diego International-Lindbergh Field", IATA: "SAN"},
                           {city: cities[120], name: "San Francisco International Airport", IATA: "SFO"},
                           {city: cities[121], name: "Pulkovo", IATA: "LED"},
                           {city: cities[122], name: "Saskatoon", IATA: "YXE"},
                           {city: cities[123], name: "Seattle-Tacoma International Airport", IATA: "SEA"},
                           {city: cities[124], name: "Vrajdebna", IATA: "SOF"},
                           {city: cities[125], name: "Zracna Luka", IATA: "SPU"},
                           {city: cities[126], name: "Sola", IATA: "SVG"},
                           {city: cities[127], name: "Echterdingen", IATA: "STR"},
                           {city: cities[128], name: "Arlanda", IATA: "ARN"},
                           {city: cities[128], name: "Bromma", IATA: "BMA"},
                           {city: cities[128], name: "Skavsta", IATA: "NYO"},
                           {city: cities[129], name: "Kingsford Smith", IATA: "SYD"},
                           {city: cities[130], name: "Ulemiste", IATA: "TLL"},
                           {city: cities[131], name: "Tampa International Airport", IATA: "TPA"},
                           {city: cities[132], name: "Ben-Gurion International Airport", IATA: "TLV"},
                           {city: cities[133], name: "Narita", IATA: "NRT"},
                           {city: cities[133], name: "Haneda", IATA: "HND"},
                           {city: cities[134], name: "Lester B. Pearson", IATA: "YYZ"},
                           {city: cities[135], name: "Blagnac", IATA: "TLS"},
                           {city: cities[136], name: "Dei Legionari", IATA: "TRS"},
                           {city: cities[137], name: "Carthage", IATA: "TUN"},
                           {city: cities[138], name: "Caselle", IATA: "TRN"},
                           {city: cities[139], name: "Vancouver International Airport", IATA: "YVR"},
                           {city: cities[140], name: "Tessera-Marco Polo", IATA: "VCE"},
                           {city: cities[141], name: "Villafranca", IATA: "VRN"},
                           {city: cities[142], name: "Schwechat", IATA: "VIE"},
                           {city: cities[143], name: "Wilno International Airport", IATA: "VNO"},
                           {city: cities[144], name: "Okęcie / im. Fryderyka Chopina", IATA: "WAW"},
                           {city: cities[144], name: "Modlin", IATA: "WMI"},
                           {city: cities[145], name: "Dulles International Airport", IATA: "IAD"},
                           {city: cities[145], name: "Ronald Reagan National Airport", IATA: "DCA"},
                           {city: cities[146], name: "Winnipeg Int. Airportman.", IATA: "YWG"},
                           {city: cities[147], name: "Pleso", IATA: "ZAG"},
                           {city: cities[148], name: "Kloten", IATA: "ZRH"}])

airplanes = Airplane.create([{name: "Boeing 747", seats: 513},
                             {name: "Boeing 747-400", seats: 1026},
                             {name: "Boeing 747-8", seats: 743},
                             {name: "Boeing 767", seats: 278},
                             {name: "Boeing 777", seats: 391},
                             {name: "Boeing 787", seats: 270},
                             {name: "Boeing 737", seats: 145},
                             {name: "Boeing 757", seats: 234},
                             {name: "Boeing 717", seats: 106},
                             {name: "Airbus A300", seats: 266},
                             {name: "Airbus A310", seats: 247},
                             {name: "Airbus A330", seats: 366},
                             {name: "Airbus A340", seats: 380},
                             {name: "Airbus A350", seats: 333},
                             {name: "Airbus A380", seats: 853},
                             {name: "Airbus A318", seats: 132},
                             {name: "Airbus A319", seats: 156},
                             {name: "Airbus A320", seats: 160},
                             {name: "Airbus A321", seats: 220}])

flight_type = FlightType.create([{name: "Przylot"}, {name: "Odlot"}])
flight_status = FlightStatus.create([{name: "Wystartował"}, {name: "Wylądował"}, {name: "Oczekiwany"}, {name: "Odwołany"}])

airlines = Airline.create([{name: "Ryanair"}, {name: "EasyJet"}, {name: "Wizz Air"}, {name: "Germanwings"}, {name: "Norwegian"},
                           {name: "LOT"}, {name: "Emirates"}, {name: "Qatar Airways"}, {name: "Turkish Airlines"}, {name: "Enter Air"},
                           {name: "Aeroflot"}, {name: "Lufthansa"}])

dep = [DateTime.new(2018, 5, 15, 10, 15, 0),
       DateTime.new(2018, 5, 15, 10, 30, 0),
       DateTime.new(2018, 5, 15, 10, 45, 0),
       DateTime.new(2018, 5, 15, 11, 00, 0),
       DateTime.new(2018, 5, 15, 12, 15, 0),
       DateTime.new(2018, 5, 15, 13, 35, 0),
       DateTime.new(2018, 5, 15, 14, 5, 0)]
arr = [DateTime.new(2018, 5, 15, 15, 55, 0),
       DateTime.new(2018, 5, 15, 16, 0, 0),
       DateTime.new(2018, 5, 15, 16, 5, 0),
       DateTime.new(2018, 5, 15, 16, 15, 0),
       DateTime.new(2018, 5, 15, 16, 25, 0),
       DateTime.new(2018, 5, 15, 16, 35, 0),
       DateTime.new(2018, 5, 15, 18, 5, 0)]

flights = []
for i in 1..1000
  type = flight_type.sample
  flights << {dep_date: dep.sample, arr_date: arr.sample, airline: airlines.sample, airport: airports.sample,
              airplane: airplanes.sample, flight_type: type, flight_status: flight_status[2]}
end
Flight.create(flights)